# Aider AI Pair Programmer Configuration
# https://aider.chat/docs/config.html

##############################################################################
# STOP! READ THIS FIRST - MANDATORY SESSION MANAGEMENT
##############################################################################
#
# BEFORE doing ANYTHING in this session, you MUST run:
#
#   uv run ai-start-task "Your task description"
#
# If you have NOT run this command yet, STOP NOW and run it!
#
# This is NOT optional. Every Aider session MUST start with ai-start-task.
#
# DURING work:
#   uv run ai-log "Progress message"
#   uv run ai-update-plan "Completed item"
#
# WHEN finishing:
#   uv run ai-finish-task --summary="What you accomplished"
#
# See AI_DOCS/ai-tools.md for complete workflow.
#
##############################################################################

##############################################################################
# SHARED DOCUMENTATION (ALWAYS READ THESE)
##############################################################################

# Read these shared documentation files for complete guidelines:
read:
  - AI_DOCS/ai-tools.md           # Session management (MANDATORY workflow)
  - AI_DOCS/tdd-workflow.md       # TDD process and testing standards
  - AI_DOCS/code-conventions.md   # Code style and best practices
  - AI_DOCS/project-context.md    # Tech stack and architecture

# These files contain the single source of truth for:
# - AI session management workflow (ai-start-task, ai-log, ai-finish-task)
# - Test-Driven Development principles and examples
# - Code quality standards and conventions
# - Project structure and dependencies

##############################################################################
# Test-Driven Development (TDD) - MANDATORY
##############################################################################

# Aider Instructions:
# - ALWAYS write tests BEFORE implementation code
# - Use real code from codebase, minimize mocks/fixtures
# - Run `make check` after every code change
# - Maintain minimum 80% test coverage
# - Follow existing test patterns in tests/

# See AI_DOCS/tdd-workflow.md for complete TDD workflow and examples

##############################################################################
# Project Configuration
##############################################################################

# Git integration
auto-commits: true
commit-prompt: |
  Generate a concise commit message following conventional commits format.
  Include emoji if appropriate.

# Testing
test-cmd: "make test"

# Linting
lint-cmd: "make lint"

# Auto-run tests after changes
auto-test: true

# Auto-run lint after changes
auto-lint: true

##############################################################################
# Code Quality Standards
##############################################################################

# Edit format
edit-format: diff

# Show diffs
show-diffs: true

# Message style
message-file: .aider.instructions.md

##############################################################################
# File Organization
##############################################################################

# Watch these files for context
watch-files:
  - "src/**/*.py"
  - "tests/**/*.py"
  - "pyproject.toml"
  - "Makefile"
  - "AGENTS.md"
  - "AI_DOCS/*.md"

# Read-only files (for context, don't edit)
read-files:
  - "README.md"
  - "CHANGES.md"
  - "PROJECT_STRUCTURE.md"
  - "AI_DOCS/tdd-workflow.md"
  - "AI_DOCS/ai-tools.md"
  - "AI_DOCS/code-conventions.md"
  - "AI_DOCS/project-context.md"

##############################################################################
# AI Behavior Settings
##############################################################################

# Show repo map for better context
map-tokens: 2048

# Use repo map
show-repo-map: true

# Cache prompts
cache-prompts: true

# Suggest shell commands for testing
suggest-shell-commands: true

##############################################################################
# Quality Gates
##############################################################################

# These commands will run before committing
# If any fail, the commit is blocked

# pre-commit-hook runs these checks:
# 1. make format - Black + isort formatting
# 2. make lint - Ruff + mypy + Pylint
# 3. make test - All tests with coverage
# 4. Coverage check - Must be ≥ 80%

##############################################################################
# Aider-Specific TDD Workflow
##############################################################################

# When user requests a feature:
# 1. Ask Aider to write tests first: "Write tests for X feature"
# 2. Run tests (they will fail): /test
# 3. Ask Aider to implement: "Implement X to make tests pass"
# 4. Run tests again (should pass): /test
# 5. Run quality check: /run make check
# 6. If all pass, commit: /commit

# See AI_DOCS/tdd-workflow.md for complete TDD examples

##############################################################################
# Example Commands
##############################################################################

# /add src/leadership_blog_generator/feature.py tests/test_feature.py
#   - Add files to chat context
#
# /test
#   - Run make test
#
# /lint
#   - Run make lint
#
# /run make check
#   - Run complete quality check (format + lint + test)
#
# /run make coverage
#   - Check test coverage
#
# /commit
#   - Commit changes if all checks pass
#
# /help
#   - Show all Aider commands

##############################################################################
# Instructions for Aider
##############################################################################

# READ THE SHARED DOCUMENTATION ABOVE (automatically included via `read:`)
# - AI_DOCS/ai-tools.md - Session management workflow (MANDATORY)
# - AI_DOCS/tdd-workflow.md - TDD process with examples
# - AI_DOCS/code-conventions.md - Code standards
# - AI_DOCS/project-context.md - Project architecture

# ALSO READ THESE UNIVERSAL INSTRUCTIONS:
# - AGENTS.md - Universal AI agent guidelines
# - CLAUDE.md - Claude Code examples (good patterns)
# - .cursorrules - Cursor AI rules (comprehensive)

# CORE RULES:
# 1. Tests first, ALWAYS (TDD)
# 2. Minimize mocks - use real code
# 3. Type hints on all functions (mypy strict)
# 4. Run `make check` before committing
# 5. Keep coverage ≥ 80%

# QUALITY GATES (all must pass):
# ✅ Tests written first
# ✅ All tests pass
# ✅ Coverage ≥ 80%
# ✅ Black formatting
# ✅ isort imports
# ✅ Ruff linting
# ✅ mypy type checking (strict)
# ✅ Pylint score 10/10
# ✅ make check passes

##############################################################################
# Project-Specific Patterns
##############################################################################

# Test file pattern
# tests/test_*.py for each src/leadership_blog_generator/*.py

# Import pattern (use package name, not src prefix):
# from leadership_blog_generator import function_name

# Type hints required (mypy strict mode):
# def func(param: str) -> int:

# Docstring style (Google format):
# """Brief description.
#
# Args:
#     param: Description
#
# Returns:
#     Description
# """

# See AI_DOCS/code-conventions.md for complete code standards

##############################################################################
# When to Mock (ONLY when necessary)
##############################################################################

# Mock these:
# - HTTP requests (requests.get, etc.)
# - Database calls
# - File I/O (destructive operations)
# - Current time (datetime.now)
# - Random values

# DON'T mock these:
# - Internal project functions
# - Pure functions
# - Data transformations
# - Business logic

# See AI_DOCS/tdd-workflow.md for complete mocking guidelines

##############################################################################
# Coverage Requirements
##############################################################################

# Minimum: 80% (enforced)
# Target: 90%+
# Ideal: 100% for new code

# Check with: /run make coverage
# View HTML report: htmlcov/index.html

# See AI_DOCS/tdd-workflow.md for coverage guidelines

##############################################################################
# Example TDD Session with Aider
##############################################################################

# User: "Add a function to parse JSON safely"
#
# You:
# > /add tests/test_utils.py src/leadership_blog_generator/utils.py
# > I'll write tests first following TDD...
#
# [Edit tests/test_utils.py - add test_parse_json_safe]
#
# > /test
# [Tests fail - function doesn't exist]
#
# > Now implementing the function...
# [Edit src/leadership_blog_generator/utils.py - add parse_json_safe]
#
# > /test
# [Tests pass]
#
# > /run make check
# [All quality checks pass]
#
# > /commit
# [Commit with message: "Add safe JSON parsing with tests"]

# See AI_DOCS/tdd-workflow.md for more complete examples

##############################################################################

# For complete guidelines, see:
# - AI_DOCS/ai-tools.md (session management - MANDATORY)
# - AI_DOCS/tdd-workflow.md (TDD process and testing)
# - AI_DOCS/code-conventions.md (code standards)
# - AI_DOCS/project-context.md (architecture and dependencies)
# - AGENTS.md (universal AI agent instructions)
